training_data = [
    ("hi", "Hello! Welcome to our hotel. How can I assist you today?"),
    ("hello", "Hi there! How can I help you?"),
    ("good morning", "Good morning! How can I assist you today?"),
    ("What rooms are available?", "show_available_rooms"),
    ("Show me available rooms", "show_available_rooms"),
    ("Do you have rooms available?", "show_available_rooms"),

    ("good evening", "Good evening! How can I help you?"),
    ("I would like a single room", "Got it. Could I have your name, please?"),
    ("I would like a double room", "Got it. Could I have your name, please?"),
   ("I'll take a suite", "Thank you! Could you tell me your name?"),
("my name is", "Thank you! Could you also provide your email address for booking confirmation?"),
("here is my email address", "Thank you! Your booking has been confirmed. We will send all the details to your email."),

    ("I need a room", "Sure! We have different types of rooms. Would you like a single, double, or suite?"),
    ("book a room for me", "Of course! Could you let me know if you prefer a single, double, or suite room?"),
    ("need a room", "We can arrange that! What type of room would you like - single, double, or suite?"),
    ("I'm in", "Great! Which type of room would you prefer - single, double, or suite?"),
    ("reserve a room for me", "I can help with that! Please let me know if you'd like a single, double, or suite room."),
    ("I agree in this fare", "Thank you for confirming! Could you tell me your name to proceed with the booking?"),
    ("I want a room", "Sure! Which type of room would you prefer - single, double, or suite?"),
    ("book a room", "I'd be happy to help with your booking! Please choose a room type: single, double, or suite."),
    ("please reserve a room", "I can do that! Would you like a single, double, or suite room?"),
    ("I'd like to book a room", "Great choice! Could you specify whether you'd like a single, double, or suite room?"),
    ("book me a room", "Of course! What type of room would you prefer - single, double, or suite?"),
    ("I want to reserve a room", "Sure! Please tell me which room type you prefer - single, double, or suite."),
    ("I'd like a room", "Got it! Could you tell me if you prefer a single, double, or suite room?"),
    ("please book a room", "Absolutely! Let me know your room preference: single, double, or suite."),
    ("do you have rooms", "Yes, we have rooms available. Would you like a single, double, or suite?"),
    ("what types of rooms do you have", "We offer single, double, and suite rooms. Which one would you like?"),
    ("I want to book a room", "Great! Could you please let me know which type of room you would prefer - single, double, or suite?"),
    ("can I reserve a room", "Of course! Please specify if you'd like a single, double, or suite."),
    ("tell me about single rooms", "Our single rooms are cozy and ideal for solo travelers. The fare is BDT 1000 per night."),
    ("what's a double room", "Double rooms are comfortable for two people with additional amenities. The fare is BDT 1500 per night."),
    ("suite details", "Suites are spacious and luxurious, perfect for families or special occasions. The fare is BDT 2000 per night."),
    ("how much does a single room cost", "The fare for a single room is BDT 1000 per night."),
    ("how much is a double room", "The fare for a double room is BDT 1500 per night."),
    ("how much for a suite", "The fare for a suite is BDT 2000 per night."),
    ("I would like a single room", "Got it. Could I have your name, please?"),
    ("I want a double room", "Sure! May I know your name?"),
    ("I'll take a suite", "Thank you! Could you tell me your name?"),
    ("my name is", "Thank you. Could you also provide your phone number?"),
    ("here is my phone number", "Got it. What is your preferred check-in date?"),
    ("that's all", "Thank you for the details. Your booking has been confirmed!"),
    ("bye", "Thank you for choosing our hotel! Have a great day!"),

    
    ("I'd like a single room for two nights", "Sure! Could I have your name to complete the booking?"),
    ("book a double room for me from 1st December", "Great! May I know your name to proceed?"),
    ("I want to reserve a suite for this weekend", "Got it! Could you provide your name and phone number for the booking?"),
    ("can you reserve a room for 3 nights from next week", "Of course! Please let me know your preferred room type: single, double, or suite."),
    ("I need a single room for two adults and one child", "Thank you! Could you tell me your name to continue with the booking?"),
    ("I would like to book a double room for the weekend", "Got it! Please tell me your name and check-in date."),
    ("please reserve a suite for 4 nights from Friday", "Sure! Could you provide your name and phone number for the booking?"),
    ("book me a room for tonight", "Could you tell me if you prefer a single, double, or suite room?"),
    ("I'd like a room with a king-sized bed", "We have that available in our suites. Could you confirm if you'd like a suite?"),
    ("reserve a double room for two people", "Sure! Can I have your name to proceed with the booking?"),
    ("I want to book a suite for my family", "Great! Could you provide your name and preferred check-in date?"),

    
    ("can I get a discount for booking a suite", "We offer seasonal discounts. Please check our website for current offers."),
    ("do you offer early check-in for suites", "Early check-in is subject to availability. Would you like to request an early check-in for your suite?"),
    ("can I see pictures of the suites", "Certainly! You can view pictures of our suites on our website, or I can send you a link."),
    ("are the rooms soundproof", "Yes, our rooms are designed to provide a quiet and peaceful stay for our guests."),
    ("do you offer free cancellation on bookings", "Yes, we offer free cancellation up to 24 hours before your scheduled check-in."),
    ("can I upgrade my room to a suite", "Room upgrades are available subject to availability. Please let us know your preferences."),
    ("I want to book a family room", "We have family rooms available! Could you tell me the check-in and check-out dates for your booking?"),
    ("do you have rooms with a balcony", "Yes, we have rooms with balconies. Would you prefer one of those?"),
    ("can I get a room with a view of the city", "We have rooms with city views. Would you like to request one of those during booking?"),
("do you have any special offers", "Yes, we have special offers available. Please check our website for the latest deals."),
("can I get a late checkout", "Late checkout is subject to availability. Would you like to request a late checkout?"),
("do you have a gym", "Yes, we have a fully equipped gym available for our guests."),
("is breakfast included", "Yes, breakfast is included with your stay."),
("do you have a swimming pool", "Yes, we have a swimming pool available for our guests."),
("can I get an extra bed", "Extra beds are available upon request. Would you like to add one to your booking?"),
("do you offer airport shuttle service", "Yes, we offer airport shuttle service. Would you like to arrange a pickup?"),
("is there free Wi-Fi", "Yes, we offer complimentary Wi-Fi for all our guests."),
("do you have a restaurant", "Yes, we have a restaurant that serves a variety of cuisines."),
("can I book a room with a sea view", "We have rooms with sea views. Would you like to book one of those?"),
("do you have a spa", "Yes, we have a spa offering various treatments. Would you like to book a session?"),
("is parking available", "Yes, we have free parking available for our guests."),
("do you allow pets", "Yes, we are a pet-friendly hotel. Would you like to bring your pet along?"),
("can I get a room with a kitchenette", "We have rooms with kitchenettes available. Would you like to book one of those?"),
("do you have conference rooms", "Yes, we have conference rooms available for meetings and events."),
("is there a bar", "Yes, we have a bar where you can enjoy a variety of drinks."),
("do you offer room service", "Yes, we offer 24/7 room service for our guests."),
("can I get a room with a bathtub", "We have rooms with bathtubs available. Would you like to book one of those?"),
("do you have laundry service", "Yes, we offer laundry service for our guests."),
("is there a business center", "Yes, we have a business center equipped with all necessary facilities."),
]

training_data.extend([
    ("I need to book a room for next week", "Of course! Could you specify if you'd like a single, double, or suite room?"),
    ("can you book a room for me for tomorrow", "Sure! Please let me know if you prefer a single, double, or suite room."),
    ("I'd like to reserve a room for my business trip", "We can help with that! Could you tell me your preferred room type: single, double, or suite?"),
    ("I want to book a room for my vacation", "Great! Could you specify if you'd like a single, double, or suite room?"),
    ("can I book a room for my honeymoon", "Congratulations! We recommend our suites for a honeymoon. Would you like to book a suite?"),
    ("I need a room for a week", "Sure! Please let me know if you prefer a single, double, or suite room."),
    ("book a room for me for the weekend", "Of course! Could you specify if you'd like a single, double, or suite room?"),
    ("I'd like to book a room for my parents", "We can arrange that! Could you tell me your preferred room type: single, double, or suite?"),
    ("reserve a room for me for next month", "Sure! Please let me know if you prefer a single, double, or suite room."),
    ("I want to book a room for my anniversary", "Happy anniversary! We recommend our suites for special occasions. Would you like to book a suite?"),
    ("can I book a room for my friend", "Of course! Could you specify if you'd like a single, double, or suite room?"),
    ("I'd like to reserve a room for my family", "We have family rooms available! Could you tell me your preferred check-in and check-out dates?"),
    ("book a room for me for tonight", "Could you tell me if you prefer a single, double, or suite room?"),
    ("I need a room for two nights", "Sure! Please let me know if you prefer a single, double, or suite room."),
    ("can you reserve a room for me for next weekend", "Of course! Could you specify if you'd like a single, double, or suite room?"),
    ("I'd like to book a room for my business trip", "We can help with that! Could you tell me your preferred room type: single, double, or suite?"),
    ("I want to book a room for my vacation", "Great! Could you specify if you'd like a single, double, or suite room?"),
    ("can I book a room for my honeymoon", "Congratulations! We recommend our suites for a honeymoon. Would you like to book a suite?"),
    ("I need a room for a week", "Sure! Please let me know if you prefer a single, double, or suite room."),
    ("book a room for me for the weekend", "Of course! Could you specify if you'd like a single, double, or suite room?"),
    ("I'd like to book a room for my parents", "We can arrange that! Could you tell me your preferred room type: single, double, or suite?"),
    ("reserve a room for me for next month", "Sure! Please let me know if you prefer a single, double, or suite room."),
    ("I want to book a room for my anniversary", "Happy anniversary! We recommend our suites for special occasions. Would you like to book a suite?"),
    ("can I book a room for my friend", "Of course! Could you specify if you'd like a single, double, or suite room?"),
    ("I'd like to reserve a room for my family", "We have family rooms available! Could you tell me your preferred check-in and check-out dates?"),
    ("book a room for me for tonight", "Could you tell me if you prefer a single, double, or suite room?"),
    ("I need a room for two nights", "Sure! Please let me know if you prefer a single, double, or suite room."),
    ("can you reserve a room for me for next weekend", "Of course! Could you specify if you'd like a single, double, or suite room?"),
])
